doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options:
                username: '%env(MONGODB_USERNAME)%'
                password: '%env(MONGODB_PASSWORD)%'
                authSource: '%env(MONGO_INITDB_DATABASE)%'
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: false
#            auto_mapping: true
            mappings:
                Product:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Infrastructure/Product/Document'
                    prefix: Infrastructure\Product\Document\
                    alias: Product
